Particles += pt_sinkStellarEvolution.o

pt_sinkStellarEvolution.o : SinkStellarEvolution.h Particles_sinkData.o pt_sinkInterface.o \
                            Driver_interface.o Driver_data.o RuntimeParameters_interface.o \
                            Timers_interface.o
