# Makefile for the basic stub level of Particles [/source/Particles]

Particles +=  \
	Particles_advance.o \
	Particles_computeDt.o \
	Particles_dump.o  \
	Particles_finalize.o \
	Particles_getGlobalNum.o \
	Particles_getLocalNum.o \
	Particles_init.o \
	Particles_initPositions.o \
	Particles_longRangeForce.o \
	Particles_putLocalNum.o \
	Particles_shortRangeForce.o \
	Particles_updateAttributes.o \
	Particles_sendOutputData.o \
	Particles_updateRefinement.o\
	Particles_unitTest.o \
	Particles_mapFromMesh.o \
	Particles_mapToMeshOneBlk.o \
	Particles_updateGridVar.o \
	Particles_interface.o \
	Particles_getCountPerBlk.o \
	Particles_accumCount.o \
	Particles_initData.o \
	Particles_initForces.o \
	Particles_manageLost.o \
	Particles_addNew.o \
	Particles_sinkAccelGasOnSinksAndSinksOnGas.o \
	Particles_sinkCreateAccrete.o \
	Particles_sinkOutflow.o \
	Particles_sinkHeating.o \
	Particles_sinkStellarEvolution.o \
	Particles_sinkSupernova.o \
	Particles_sinkAdvanceParticles.o \
	Particles_sinkComputeDt.o \
	Particles_sinkInit.o \
	Particles_sinkMarkRefineDerefine.o \
	Particles_sinkMoveParticles.o \
	Particles_sinkSortParticles.o \
	Particles_sinkSyncWithParticles.o \
	Particles_PICComputeDt.o \
	Particles_CRComputeDt.o \
	Particles_massiveMarkRefineDerefine.o \
	Particles_splitting.o \
	Particles_dynamicCreationDestruction.o \
	Particles_setTag.o \
	Particles_getTag.o
